# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 17:13
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Please specify your game name')),
                ('description', models.TextField(max_length=250)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='logo')),
                ('resource_info', models.URLField(help_text='Please specify the URL')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('developer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Game',
                'ordering': ['upload_date'],
            },
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_state', models.TextField(blank=True, max_length=500)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_state', to='gamestoredata.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GameState',
                'ordering': ['last_modified'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('game_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_details', to='gamestoredata.Game')),
                ('player_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Purchase',
                'ordering': ['purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('score', models.BigIntegerField(default=0)),
                ('game_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_info', to='gamestoredata.Game')),
                ('player_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Score',
                'ordering': ['last_played'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='picture')),
                ('user_type', models.CharField(choices=[('D', 'Developer'), ('P', 'Player')], default='P', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
        migrations.AlterUniqueTogether(
            name='gamestate',
            unique_together=set([('game', 'player')]),
        ),
    ]
